name: DEPLOY TO QA

on:
  push:
    branches:
      - develop

jobs:
  build-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: yarn install

      - name: Code linting
        run: yarn lint

      - name: Building the project
        env:
          VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: yarn build
      
      - name: Debug
        env:
          VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        run: echo "Application name:$VUE_APP_NAME"
      
      - uses: actions/download-artifact@v3
        with:
          name: ./dist
          
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
