name: DEPLOY TO QA

on:
  push:
    branches:
      - develop

jobs:
  build-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Installing project dependencies
        run: yarn install

      - name: Code linting
        run: yarn lint

      - name: Building the project
        run: yarn build

      - name: Building the project
        run: yarn build
      
      - name: Debug
        run: echo "Application name:${{secrets.VUE_APP_NAME}}"  